[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tempdir = "0.3.7"
bcrypt = "0.17.0"
serde_json = "1.0.140"
clap = { version = "4.5.36", features = ["derive"] }
